# Generated by Django 3.1.14 on 2022-01-25 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exammodel',
            name='Age',
        ),
        migrations.RemoveField(
            model_name='exammodel',
            name='Branch',
        ),
        migrations.RemoveField(
            model_name='exammodel',
            name='Email',
        ),
        migrations.RemoveField(
            model_name='exammodel',
            name='Mobile',
        ),
        migrations.RemoveField(
            model_name='exammodel',
            name='Name',
        ),
        migrations.RemoveField(
            model_name='exammodel',
            name='Qualification',
        ),
    ]
